pr_rule(go(X,Y),[in(X,..(1,5)),#\=(X,1),Y=a,builtin(labeling([],[X]))]).
pr_rule(p(X),[#>(X,3),not(q(X))]).
pr_rule(q(X),[not(p(X))]).
pr_rule(not(o_q1(X)),[p(X)]).
pr_rule(not(q(_X0)),[not(o_q1(_X0))]).
pr_rule(not(o_p1(X)),[#=<(X,3)]).
pr_rule(not(o_p1(X)),[#>(X,3),q(X)]).
pr_rule(not(p(_X0)),[not(o_p1(_X0))]).
pr_rule(not(builtin(_X0)),[]).
pr_rule(not(o_go1(X,Y)),[print(not(in(X,..(1,5))))]).
pr_rule(not(o_go1(X,Y)),[in(X,..(1,5)),#=(X,1)]).
pr_rule(not(o_go1(X,Y)),[in(X,..(1,5)),#\=(X,1),Y\=a]).
pr_rule(not(go(_X0,_X1)),[not(o_go1(_X0,_X1))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
