clauses_solve(passed(34, solve/8)).
clauses_solve(passed(35, solve/8)).
clauses_solve(passed(48, proved_relatives/3)). 
clauses_solve(passed(50, proved_relatives/3)).
clauses_solve(passed(83, check_goal_/9)).
clauses_solve(passed(94, check_goal_/9)).
clauses_solve(passed(100, check_goal_/9)).
clauses_solve(passed(108, check_goal_/9)). 
clauses_solve(passed(113, mark_prev_goal/3)).
clauses_solve(passed(114, mark_prev_goal/3)).
clauses_solve(passed(115, mark_prev_goal/3)).
clauses_solve(passed(121, dynamic_consistency_check/3)).
clauses_solve(passed(130, dynamic_consistency_check/3)).
clauses_solve(passed(133, dynamic_consistency_eval/3)).
clauses_solve(passed(134, dynamic_consistency_eval/3)).
clauses_solve(passed(138, dynamic_consistency_eval_/3)).
clauses_solve(passed(141, dynamic_consistency_eval_/3)).
clauses_solve(passed(144, dynamic_consistency_eval_/3)).
clauses_solve(passed(157, solve_goal/8)).
clauses_solve(passed(169, solve_goal/8)).
clauses_solve(passed(178, solve_goal/8)).
clauses_solve(passed(182, solve_goal/8)).
clauses_solve(passed(191, solve_goal/8)).
clauses_solve(passed(195, solve_goal/8)).
clauses_solve(passed(200, solve_goal/8)).
clauses_solve(passed(205, solve_goal/8)).
clauses_solve(passed(210, solve_goal/8)).
clauses_solve(passed(222, solve_goal/8)).
clauses_solve(passed(236, solve_goal_forall/8)).
clauses_solve(passed(278, check_unbound/2)).
clauses_solve(passed(280, check_unbound/2)).
clauses_solve(passed(282, check_unbound/2)).
clauses_solve(passed(285, check_unbound/2)).
clauses_solve(passed(288, exec_with_clpq_constraints/11)).
clauses_solve(passed(290, exec_with_clpq_constraints/11)).
clauses_solve(passed(340, exec_with_neg_list/10)).
clauses_solve(passed(341, exec_with_neg_list/10)).
clauses_solve(passed(361, solve_goal_table_predicate/8)).
clauses_solve(passed(374, solve_goal_predicate/8)).
clauses_solve(passed(385, solve_goal_builtin/2)).
clauses_solve(passed(388, solve_goal_builtin/2)).
clauses_solve(passed(391, solve_goal_builtin/2)).
clauses_solve(passed(395, solve_goal_builtin/2)).
clauses_solve(passed(399, solve_goal_builtin/2)).
clauses_solve(passed(403, solve_goal_builtin/2)).
clauses_solve(passed(408, solve_goal_builtin/2)).
clauses_solve(passed(413, solve_goal_builtin/2)).
clauses_solve(passed(420, exec_goal/1)).
clauses_solve(passed(424, exec_goal/1)).
clauses_solve(passed(436, exec_findall/8)).
clauses_solve(passed(454, process_vsmlist_/4)).
clauses_solve(passed(455, process_vsmlist_/4)).
clauses_solve(passed(475, check_CHS/6)).
clauses_solve(passed(482, check_CHS/6)).
clauses_solve(passed(487, check_CHS/6)).
clauses_solve(passed(492, check_CHS/6)).
clauses_solve(passed(497, check_CHS/6)).
clauses_solve(passed(505, check_CHS/6)).
clauses_solve(passed(513, check_CHS/6)).
clauses_solve(passed(525, neg_in_stack/3)).
clauses_solve(passed(530, neg_in_stack/3)).
clauses_solve(passed(535, is_negated_goal/2)).
clauses_solve(passed(557, ground_neg_in_stack/3)).
clauses_solve(passed(564, ground_neg_in_stack/3)).
clauses_solve(passed(571, ground_neg_in_stack/3)).
clauses_solve(passed(573, gn_match/4)).
clauses_solve(passed(574, gn_match/4)).
clauses_solve(passed(575, gn_match/4)).
clauses_solve(passed(585, constrained_neg_in_stack/3)).
clauses_solve(passed(592, contrained_neg/2)).
clauses_solve(passed(599, contrained_neg/2)).
clauses_solve(passed(606, contrained_neg/2)).
clauses_solve(passed(617, proved_in_stack/2)).
clauses_solve(passed(630, check_parents/3)).
clauses_solve(passed(633, check_parents/3)).
clauses_solve(passed(636, check_parents/4)).
clauses_solve(passed(643, check_parents/4)).
clauses_solve(passed(654, even_loop/2)).
clauses_solve(passed(658, even_loop/2)).
clauses_solve(passed(664, type_loop_fail_pos/2)).
clauses_solve(passed(664, type_loop_fail_pos/2)).
clauses_solve(passed(664, type_loop_fail_pos/2)).
clauses_solve(passed(683, stack_parents/3)).
clauses_solve(passed(687, stack_parents/3)).
clauses_solve(passed(711, stack_proved/5)).
clauses_solve(passed(712, stack_proved/5)).
clauses_solve(passed(727, add_proved/4)).
clauses_solve(passed(729, add_proved/4)).
clauses_solve(passed(731, add_proved/4)).
clauses_solve(passed(733, add_proved/4)).
clauses_solve(passed(752, solve_c_forall/8)).
clauses_solve(passed(846, solve_var_forall_/11)).
clauses_solve(passed(848, solve_var_forall_/11)).
clauses_solve(passed(888, append_set/3)).
clauses_solve(passed(892, append_set/3)).
clauses_solve(passed(895, memberchk_oc/2)).
clauses_solve(passed(906, apply_constraint/1)).
clauses_solve(passed(908, apply_constraint/1)).
clauses_solve(passed(910, apply_constraint/1)).
clauses_solve(passed(928, find_duals/4)).
clauses_solve(passed(941, make_duals_/4)).
clauses_solve(passed(942, make_duals_/4)).
clauses_solve(passed(957, dual/2)).
clauses_solve(passed(958, dual/2)).
clauses_solve(passed(959, dual/2)).
clauses_solve(passed(960, dual/2)).
clauses_solve(passed(961, dual/2)).
clauses_solve(passed(963, dual/2)).
clauses_solve(passed(964, dual/2)).
clauses_solve(passed(976, dump_constraint/5)).
clauses_solve(passed(979, dump_constraint/5)).
clauses_solve(passed(985, dump_constraint/5)).
clauses_solve(passed(991, clp_vars_in/2)).
clauses_solve(passed(1001, collect_vars_/4)).
clauses_solve(passed(1003, collect_vars_/4)).
