pr_rule(bird(sam),[]).
pr_rule(bird(tweety),[]).
pr_rule(bird(john),[]).
pr_rule(ab(X),[penguin(X)]).
pr_rule(ab(X),[wounded_bird(X)]).
pr_rule(flies(X),[bird(X),not(ab(X))]).
pr_rule(wounded_bird(X),[not(o_wounded_bird(X)),abducible(wounded_bird(X))]).
pr_rule(o_wounded_bird(X),[not(wounded_bird(X))]).
pr_rule(abducible(wounded_bird(X)),[not(o_abducible(wounded_bird(X)))]).
pr_rule(o_abducible(wounded_bird(X)),[not(abducible(wounded_bird(X)))]).
pr_rule(penguin(X),[not(o_penguin(X)),abducible(penguin(X))]).
pr_rule(o_penguin(X),[not(penguin(X))]).
pr_rule(abducible(penguin(X)),[not(o_abducible(penguin(X)))]).
pr_rule(o_abducible(penguin(X)),[not(abducible(penguin(X)))]).
pr_rule(ab(X),[not(o_ab(X)),abducible(ab(X))]).
pr_rule(o_ab(X),[not(ab(X))]).
pr_rule(abducible(ab(X)),[not(o_abducible(ab(X)))]).
pr_rule(o_abducible(ab(X)),[not(abducible(ab(X)))]).
pr_rule(not(o__ab1(X)),[ab(X)]).
pr_rule(not(o_ab(_X0)),[not(o__ab1(_X0))]).
pr_rule(not(o__penguin1(X)),[penguin(X)]).
pr_rule(not(o_penguin(_X0)),[not(o__penguin1(_X0))]).
pr_rule(not(o__abducible1(_Z0,X)),[_Z0\=wounded_bird(X)]).
pr_rule(not(o__abducible1(_Z0,X)),[_Z0=wounded_bird(X),abducible(wounded_bird(X))]).
pr_rule(not(o__abducible1(_Z0)),[forall(X,not(o__abducible1(_Z0,X)))]).
pr_rule(not(o__abducible2(_Z0,X)),[_Z0\=penguin(X)]).
pr_rule(not(o__abducible2(_Z0,X)),[_Z0=penguin(X),abducible(penguin(X))]).
pr_rule(not(o__abducible2(_Z0)),[forall(X,not(o__abducible2(_Z0,X)))]).
pr_rule(not(o__abducible3(_Z0,X)),[_Z0\=ab(X)]).
pr_rule(not(o__abducible3(_Z0,X)),[_Z0=ab(X),abducible(ab(X))]).
pr_rule(not(o__abducible3(_Z0)),[forall(X,not(o__abducible3(_Z0,X)))]).
pr_rule(not(o_abducible(_X0)),[not(o__abducible1(_X0)),not(o__abducible2(_X0)),not(o__abducible3(_X0))]).
pr_rule(not(o_abducible1(_Z0,X)),[_Z0\=wounded_bird(X)]).
pr_rule(not(o_abducible1(_Z0,X)),[_Z0=wounded_bird(X),o_abducible(wounded_bird(X))]).
pr_rule(not(o_abducible1(_Z0)),[forall(X,not(o_abducible1(_Z0,X)))]).
pr_rule(not(o_abducible2(_Z0,X)),[_Z0\=penguin(X)]).
pr_rule(not(o_abducible2(_Z0,X)),[_Z0=penguin(X),o_abducible(penguin(X))]).
pr_rule(not(o_abducible2(_Z0)),[forall(X,not(o_abducible2(_Z0,X)))]).
pr_rule(not(o_abducible3(_Z0,X)),[_Z0\=ab(X)]).
pr_rule(not(o_abducible3(_Z0,X)),[_Z0=ab(X),o_abducible(ab(X))]).
pr_rule(not(o_abducible3(_Z0)),[forall(X,not(o_abducible3(_Z0,X)))]).
pr_rule(not(abducible(_X0)),[not(o_abducible1(_X0)),not(o_abducible2(_X0)),not(o_abducible3(_X0))]).
pr_rule(not(o__wounded_bird1(X)),[wounded_bird(X)]).
pr_rule(not(o_wounded_bird(_X0)),[not(o__wounded_bird1(_X0))]).
pr_rule(not(o_flies1(X)),[not(bird(X))]).
pr_rule(not(o_flies1(X)),[bird(X),ab(X)]).
pr_rule(not(flies(_X0)),[not(o_flies1(_X0))]).
pr_rule(not(o_wounded_bird1(X)),[o_wounded_bird(X)]).
pr_rule(not(o_wounded_bird1(X)),[not(o_wounded_bird(X)),not(abducible(wounded_bird(X)))]).
pr_rule(not(wounded_bird(_X0)),[not(o_wounded_bird1(_X0))]).
pr_rule(not(o_penguin1(X)),[o_penguin(X)]).
pr_rule(not(o_penguin1(X)),[not(o_penguin(X)),not(abducible(penguin(X)))]).
pr_rule(not(penguin(_X0)),[not(o_penguin1(_X0))]).
pr_rule(not(o_ab1(X)),[not(penguin(X))]).
pr_rule(not(o_ab2(X)),[not(wounded_bird(X))]).
pr_rule(not(o_ab3(X)),[o_ab(X)]).
pr_rule(not(o_ab3(X)),[not(o_ab(X)),not(abducible(ab(X)))]).
pr_rule(not(ab(_X0)),[not(o_ab1(_X0)),not(o_ab2(_X0)),not(o_ab3(_X0))]).
pr_rule(not(o_bird1(_X0)),[_X0\=sam]).
pr_rule(not(o_bird2(_X0)),[_X0\=tweety]).
pr_rule(not(o_bird3(_X0)),[_X0\=john]).
pr_rule(not(bird(_X0)),[not(o_bird1(_X0)),not(o_bird2(_X0)),not(o_bird3(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
