



compile:
	ciaoc -o new_hanoi_3 new_hanoi_3.pl


test:
	./new_hanoi_3 3
	./new_hanoi_3 4
	./new_hanoi_3 5
	./new_hanoi_3 6
	./new_hanoi_3 8
	./new_hanoi_3 10
	echo ------- --------
	./new_hanoi_3 7
	./new_hanoi_3 9
