pr_rule((test X),[not(test2(X,Y))]).
pr_rule((test X),[]).
pr_rule(test2(X,Y),[Y\=1,not(test3(X))]).
pr_rule(test2(X,1),[not(test3(X))]).
pr_rule(test3(X),[not((test X))]).
pr_rule(male(bob),[]).
pr_rule(male(bo),[]).
pr_rule(male(ben),[]).
pr_rule(male(jeff),[]).
pr_rule(male(ron),[]).
pr_rule(male(tim),[]).
pr_rule(male(ray),[]).
pr_rule(female(may),[]).
pr_rule(female(joy),[]).
pr_rule(female(jill),[]).
pr_rule(female(kathy),[]).
pr_rule(female(ali),[]).
pr_rule(female(sam),[]).
pr_rule(female(beth),[]).
pr_rule(father(bob,jill),[]).
pr_rule(father(bob,bo),[]).
pr_rule(father(bo,ali),[]).
pr_rule(father(ben,sam),[]).
pr_rule(mother(may,jill),[]).
pr_rule(mother(may,bo),[]).
pr_rule(mother(joy,ali),[]).
pr_rule(mother(jill,sam),[]).
pr_rule(parent(X,Y),[father(X,Y)]).
pr_rule(parent(X,Y),[mother(X,Y)]).
pr_rule(grandparent(X,Y),[parent(X,Z),parent(Z,Y)]).
pr_rule(ancestor(X,Y),[parent(X,Y)]).
pr_rule(ancestor(X,Y),[parent(X,Z),ancestor(Z,Y)]).
pr_rule(sibling(X,Y),[X\=Y,parent(Z,X),parent(Z,Y)]).
pr_rule(sister(X,Y),[sibling(X,Y),female(X)]).
pr_rule(brother(X,Y),[sibling(X,Y),male(X)]).
pr_rule(cousin(X,Y),[parent(P1,X),parent(P2,Y),P1\=P2]).
pr_rule(hardmath(X),[X is A+(B*C-(D/E-F)*G)*H]).
pr_rule(not(o_hardmath1(X,A,B,C,D,E,F,G,H)),[not(X is A+(B*C-(D/E-F)*G)*H)]).
pr_rule(not(o_hardmath1(X)),[forall(A,forall(B,forall(C,forall(D,forall(E,forall(F,forall(G,forall(H,not(o_hardmath1(X,A,B,C,D,E,F,G,H))))))))))]).
pr_rule(not(hardmath(_X0)),[not(o_hardmath1(_X0))]).
pr_rule(not(o_cousin1(X,Y,P1,P2)),[not(parent(P1,X))]).
pr_rule(not(o_cousin1(X,Y,P1,P2)),[parent(P1,X),not(parent(P2,Y))]).
pr_rule(not(o_cousin1(X,Y,P1,P2)),[parent(P1,X),parent(P2,Y),P1=P2]).
pr_rule(not(o_cousin1(X,Y)),[forall(P1,forall(P2,not(o_cousin1(X,Y,P1,P2))))]).
pr_rule(not(cousin(_X0,_X1)),[not(o_cousin1(_X0,_X1))]).
pr_rule(not(o_brother1(X,Y)),[not(sibling(X,Y))]).
pr_rule(not(o_brother1(X,Y)),[sibling(X,Y),not(male(X))]).
pr_rule(not(brother(_X0,_X1)),[not(o_brother1(_X0,_X1))]).
pr_rule(not(o_sister1(X,Y)),[not(sibling(X,Y))]).
pr_rule(not(o_sister1(X,Y)),[sibling(X,Y),not(female(X))]).
pr_rule(not(sister(_X0,_X1)),[not(o_sister1(_X0,_X1))]).
pr_rule(not(o_sibling1(X,Y,Z)),[X=Y]).
pr_rule(not(o_sibling1(X,Y,Z)),[X\=Y,not(parent(Z,X))]).
pr_rule(not(o_sibling1(X,Y,Z)),[X\=Y,parent(Z,X),not(parent(Z,Y))]).
pr_rule(not(o_sibling1(X,Y)),[forall(Z,not(o_sibling1(X,Y,Z)))]).
pr_rule(not(sibling(_X0,_X1)),[not(o_sibling1(_X0,_X1))]).
pr_rule(not(o_ancestor1(X,Y)),[not(parent(X,Y))]).
pr_rule(not(o_ancestor2(X,Y,Z)),[not(parent(X,Z))]).
pr_rule(not(o_ancestor2(X,Y,Z)),[parent(X,Z),not(ancestor(Z,Y))]).
pr_rule(not(o_ancestor2(X,Y)),[forall(Z,not(o_ancestor2(X,Y,Z)))]).
pr_rule(not(ancestor(_X0,_X1)),[not(o_ancestor1(_X0,_X1)),not(o_ancestor2(_X0,_X1))]).
pr_rule(not(o_grandparent1(X,Y,Z)),[not(parent(X,Z))]).
pr_rule(not(o_grandparent1(X,Y,Z)),[parent(X,Z),not(parent(Z,Y))]).
pr_rule(not(o_grandparent1(X,Y)),[forall(Z,not(o_grandparent1(X,Y,Z)))]).
pr_rule(not(grandparent(_X0,_X1)),[not(o_grandparent1(_X0,_X1))]).
pr_rule(not(o_parent1(X,Y)),[not(father(X,Y))]).
pr_rule(not(o_parent2(X,Y)),[not(mother(X,Y))]).
pr_rule(not(parent(_X0,_X1)),[not(o_parent1(_X0,_X1)),not(o_parent2(_X0,_X1))]).
pr_rule(not(o_mother1(_X0,_X1)),[_X0\=may]).
pr_rule(not(o_mother1(_X0,_X1)),[_X0=may,_X1\=jill]).
pr_rule(not(o_mother2(_X0,_X1)),[_X0\=may]).
pr_rule(not(o_mother2(_X0,_X1)),[_X0=may,_X1\=bo]).
pr_rule(not(o_mother3(_X0,_X1)),[_X0\=joy]).
pr_rule(not(o_mother3(_X0,_X1)),[_X0=joy,_X1\=ali]).
pr_rule(not(o_mother4(_X0,_X1)),[_X0\=jill]).
pr_rule(not(o_mother4(_X0,_X1)),[_X0=jill,_X1\=sam]).
pr_rule(not(mother(_X0,_X1)),[not(o_mother1(_X0,_X1)),not(o_mother2(_X0,_X1)),not(o_mother3(_X0,_X1)),not(o_mother4(_X0,_X1))]).
pr_rule(not(o_father1(_X0,_X1)),[_X0\=bob]).
pr_rule(not(o_father1(_X0,_X1)),[_X0=bob,_X1\=jill]).
pr_rule(not(o_father2(_X0,_X1)),[_X0\=bob]).
pr_rule(not(o_father2(_X0,_X1)),[_X0=bob,_X1\=bo]).
pr_rule(not(o_father3(_X0,_X1)),[_X0\=bo]).
pr_rule(not(o_father3(_X0,_X1)),[_X0=bo,_X1\=ali]).
pr_rule(not(o_father4(_X0,_X1)),[_X0\=ben]).
pr_rule(not(o_father4(_X0,_X1)),[_X0=ben,_X1\=sam]).
pr_rule(not(father(_X0,_X1)),[not(o_father1(_X0,_X1)),not(o_father2(_X0,_X1)),not(o_father3(_X0,_X1)),not(o_father4(_X0,_X1))]).
pr_rule(not(o_female1(_X0)),[_X0\=may]).
pr_rule(not(o_female2(_X0)),[_X0\=joy]).
pr_rule(not(o_female3(_X0)),[_X0\=jill]).
pr_rule(not(o_female4(_X0)),[_X0\=kathy]).
pr_rule(not(o_female5(_X0)),[_X0\=ali]).
pr_rule(not(o_female6(_X0)),[_X0\=sam]).
pr_rule(not(o_female7(_X0)),[_X0\=beth]).
pr_rule(not(female(_X0)),[not(o_female1(_X0)),not(o_female2(_X0)),not(o_female3(_X0)),not(o_female4(_X0)),not(o_female5(_X0)),not(o_female6(_X0)),not(o_female7(_X0))]).
pr_rule(not(o_male1(_X0)),[_X0\=bob]).
pr_rule(not(o_male2(_X0)),[_X0\=bo]).
pr_rule(not(o_male3(_X0)),[_X0\=ben]).
pr_rule(not(o_male4(_X0)),[_X0\=jeff]).
pr_rule(not(o_male5(_X0)),[_X0\=ron]).
pr_rule(not(o_male6(_X0)),[_X0\=tim]).
pr_rule(not(o_male7(_X0)),[_X0\=ray]).
pr_rule(not(male(_X0)),[not(o_male1(_X0)),not(o_male2(_X0)),not(o_male3(_X0)),not(o_male4(_X0)),not(o_male5(_X0)),not(o_male6(_X0)),not(o_male7(_X0))]).
pr_rule(not(o_test31(X)),[(test X)]).
pr_rule(not(test3(_X0)),[not(o_test31(_X0))]).
pr_rule(not(o_test21(X,Y)),[Y=1]).
pr_rule(not(o_test21(X,Y)),[Y\=1,test3(X)]).
pr_rule(not(o_test22(X,_X1)),[_X1\=1]).
pr_rule(not(o_test22(X,_X1)),[_X1=1,test3(X)]).
pr_rule(not(test2(_X0,_X1)),[not(o_test21(_X0,_X1)),not(o_test22(_X0,_X1))]).
pr_rule(not(o_test1(X,Y)),[test2(X,Y)]).
pr_rule(not(o_test1(X)),[forall(Y,not(o_test1(X,Y)))]).
pr_rule(not((test _X0)),[not(o_test1(_X0)),not(o_test2(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o__chk11(X)),[(test X)]).
pr_rule(not(o__chk11(X)),[not((test X)),test3(X)]).
pr_rule(not(o_chk1(_X0)),[not(o__chk11(_X0))]).
pr_rule(not(o__chk21(X,Y)),[test2(X,Y)]).
pr_rule(not(o__chk21(X,Y)),[not(test2(X,Y)),(test X)]).
pr_rule(not(o__chk21(X)),[forall(Y,not(o__chk21(X,Y)))]).
pr_rule(not(o_chk2(_X0)),[not(o__chk21(_X0))]).
pr_rule(not(o__chk31(X,_X1)),[_X1\=1]).
pr_rule(not(o__chk31(X,_X1)),[_X1=1,test3(X)]).
pr_rule(not(o__chk31(X,_X1)),[_X1=1,not(test3(X)),test2(X,1)]).
pr_rule(not(o_chk3(_X0,_X1)),[not(o__chk31(_X0,_X1))]).
pr_rule(not(o__chk41(X,Y)),[Y=1]).
pr_rule(not(o__chk41(X,Y)),[Y\=1,test3(X)]).
pr_rule(not(o__chk41(X,Y)),[Y\=1,not(test3(X)),test2(X,Y)]).
pr_rule(not(o_chk4(_X0,_X1)),[not(o__chk41(_X0,_X1))]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[forall(_X0,not(o_chk1(_X0))),forall(_X0,not(o_chk2(_X0))),forall(_X0,forall(_X1,not(o_chk3(_X0,_X1)))),forall(_X0,forall(_X1,not(o_chk4(_X0,_X1))))]).
pr_rule(add_to_query,[o_nmr_check]).
