pr_rule(eligible(X),[highGPA(X)]).
pr_rule(eligible(X),[special(X),fairGPA(X)]).
pr_rule(-eligible(X),[-special(X),-highGPA(X)]).
pr_rule(interview(X),[not(eligible(X)),not(-eligible(X))]).
pr_rule(fairGPA(john),[]).
pr_rule(-highGPA(john),[]).
pr_rule(not(o_interview1(X)),[eligible(X)]).
pr_rule(not(o_interview1(X)),[not(eligible(X)),-eligible(X)]).
pr_rule(not(interview(_X0)),[not(o_interview1(_X0))]).
pr_rule(not(o_c_highGPA1(_X0)),[_X0\=john]).
pr_rule(not(-highGPA(_X0)),[not(o_c_highGPA1(_X0))]).
pr_rule(not(-special(_X0)),[]).
pr_rule(not(o_c_eligible1(X)),[not(-special(X))]).
pr_rule(not(o_c_eligible1(X)),[-special(X),not(-highGPA(X))]).
pr_rule(not(-eligible(_X0)),[not(o_c_eligible1(_X0))]).
pr_rule(not(o_fairGPA1(_X0)),[_X0\=john]).
pr_rule(not(fairGPA(_X0)),[not(o_fairGPA1(_X0))]).
pr_rule(not(special(_X0)),[]).
pr_rule(not(highGPA(_X0)),[]).
pr_rule(not(o_eligible1(X)),[not(highGPA(X))]).
pr_rule(not(o_eligible2(X)),[not(special(X))]).
pr_rule(not(o_eligible2(X)),[special(X),not(fairGPA(X))]).
pr_rule(not(eligible(_X0)),[not(o_eligible1(_X0)),not(o_eligible2(_X0))]).
pr_rule(not(o__false1(_X0)),[not(-highGPA(_X0))]).
pr_rule(not(o__false1(_X0)),[-highGPA(_X0),not(highGPA(_X0))]).
pr_rule(not(o__false1),[forall(_X0,not(o__false1(_X0)))]).
pr_rule(not(o__false2(_X0)),[not(-special(_X0))]).
pr_rule(not(o__false2(_X0)),[-special(_X0),not(special(_X0))]).
pr_rule(not(o__false2),[forall(_X0,not(o__false2(_X0)))]).
pr_rule(not(o__false3(_X0)),[not(-eligible(_X0))]).
pr_rule(not(o__false3(_X0)),[-eligible(_X0),not(eligible(_X0))]).
pr_rule(not(o__false3),[forall(_X0,not(o__false3(_X0)))]).
pr_rule(not(o_false),[not(o__false1),not(o__false2),not(o__false3)]).
pr_rule(not(o__chk11(_X0)),[not(-highGPA(_X0))]).
pr_rule(not(o__chk11(_X0)),[-highGPA(_X0),not(highGPA(_X0))]).
pr_rule(not(o__chk11),[forall(_X0,not(o__chk11(_X0)))]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21(_X0)),[not(-special(_X0))]).
pr_rule(not(o__chk21(_X0)),[-special(_X0),not(special(_X0))]).
pr_rule(not(o__chk21),[forall(_X0,not(o__chk21(_X0)))]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o__chk31(_X0)),[not(-eligible(_X0))]).
pr_rule(not(o__chk31(_X0)),[-eligible(_X0),not(eligible(_X0))]).
pr_rule(not(o__chk31),[forall(_X0,not(o__chk31(_X0)))]).
pr_rule(not(o_chk3),[not(o__chk31)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2),not(o_chk3)]).
pr_rule(add_to_query,[o_nmr_check]).
