pr_rule(n(0),[]).
pr_rule(n(s(X)),[n(X)]).
pr_rule(p(X,Y),[not(q(X)),t(Y,Y)]).
pr_rule(q(X),[not(p(X,Y))]).
pr_rule(r(V),[r(V2)]).
pr_rule(r(3.14),[]).
pr_rule(s(N),[N\=3.14]).
pr_rule(t(A,A),[]).
pr_rule(not(o_s1(N)),[N=3.14]).
pr_rule(not(s(_X0)),[not(o_s1(_X0))]).
pr_rule(not(o_r1(V,V2)),[not(r(V2))]).
pr_rule(not(o_r1(V)),[forall(V2,not(o_r1(V,V2)))]).
pr_rule(not(o_r2(_X0)),[_X0\=3.14]).
pr_rule(not(r(_X0)),[not(o_r1(_X0)),not(o_r2(_X0))]).
pr_rule(not(o_t1(A,_X1)),[_X1\=A]).
pr_rule(not(t(_X0,_X1)),[not(o_t1(_X0,_X1))]).
pr_rule(not(o_q1(X,Y)),[p(X,Y)]).
pr_rule(not(o_q1(X)),[forall(Y,not(o_q1(X,Y)))]).
pr_rule(not(q(_X0)),[not(o_q1(_X0))]).
pr_rule(not(o_p1(X,Y)),[q(X)]).
pr_rule(not(o_p1(X,Y)),[not(q(X)),not(t(Y,Y))]).
pr_rule(not(p(_X0,_X1)),[not(o_p1(_X0,_X1))]).
pr_rule(not(o_d_n1(_X0)),[_X0\=0]).
pr_rule(not(o_d_n2(_Z0,X)),[_Z0\=s(X)]).
pr_rule(not(o_d_n2(_Z0,X)),[_Z0=s(X),not(n(X))]).
pr_rule(not(o_d_n2(_Z0)),[forall(X,not(o_d_n2(_Z0,X)))]).
pr_rule(not(n(_X0)),[not(o_d_n1(_X0)),not(o_d_n2(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
