pr_rule(bird(tux),[]).
pr_rule(penguin(tux),[]).
pr_rule(bird(tweety),[]).
pr_rule(chicken(tweety),[]).
pr_rule(flies(tux),[bird(tux),not(-flies(tux))]).
pr_rule(-flies(tux),[bird(tux),not(flies(tux))]).
pr_rule(-flies(tux),[penguin(tux)]).
pr_rule(flies(tweety),[bird(tweety),not(-flies(tweety))]).
pr_rule(-flies(tweety),[bird(tweety),not(flies(tweety))]).
pr_rule(-flies(tweety),[penguin(tweety)]).
pr_rule(flies(tux),[]).
pr_rule(not(o_c_flies1(_X0)),[_X0\=tux]).
pr_rule(not(o_c_flies1(_X0)),[_X0=tux,not(bird(tux))]).
pr_rule(not(o_c_flies1(_X0)),[_X0=tux,bird(tux),flies(tux)]).
pr_rule(not(o_c_flies2(_X0)),[_X0\=tux]).
pr_rule(not(o_c_flies2(_X0)),[_X0=tux,not(penguin(tux))]).
pr_rule(not(o_c_flies3(_X0)),[_X0\=tweety]).
pr_rule(not(o_c_flies3(_X0)),[_X0=tweety,not(bird(tweety))]).
pr_rule(not(o_c_flies3(_X0)),[_X0=tweety,bird(tweety),flies(tweety)]).
pr_rule(not(o_c_flies4(_X0)),[_X0\=tweety]).
pr_rule(not(o_c_flies4(_X0)),[_X0=tweety,not(penguin(tweety))]).
pr_rule(not(-flies(_X0)),[not(o_c_flies1(_X0)),not(o_c_flies2(_X0)),not(o_c_flies3(_X0)),not(o_c_flies4(_X0))]).
pr_rule(not(o_flies1(_X0)),[_X0\=tux]).
pr_rule(not(o_flies1(_X0)),[_X0=tux,not(bird(tux))]).
pr_rule(not(o_flies1(_X0)),[_X0=tux,bird(tux),-flies(tux)]).
pr_rule(not(o_flies2(_X0)),[_X0\=tweety]).
pr_rule(not(o_flies2(_X0)),[_X0=tweety,not(bird(tweety))]).
pr_rule(not(o_flies2(_X0)),[_X0=tweety,bird(tweety),-flies(tweety)]).
pr_rule(not(o_flies3(_X0)),[_X0\=tux]).
pr_rule(not(flies(_X0)),[not(o_flies1(_X0)),not(o_flies2(_X0)),not(o_flies3(_X0))]).
pr_rule(not(o_chicken1(_X0)),[_X0\=tweety]).
pr_rule(not(chicken(_X0)),[not(o_chicken1(_X0))]).
pr_rule(not(o_penguin1(_X0)),[_X0\=tux]).
pr_rule(not(penguin(_X0)),[not(o_penguin1(_X0))]).
pr_rule(not(o_bird1(_X0)),[_X0\=tux]).
pr_rule(not(o_bird2(_X0)),[_X0\=tweety]).
pr_rule(not(bird(_X0)),[not(o_bird1(_X0)),not(o_bird2(_X0))]).
pr_rule(not(o__false1),[not(flies(tux))]).
pr_rule(not(o__false1),[flies(tux),not(-flies(tux))]).
pr_rule(not(o__false2),[not(flies(tweety))]).
pr_rule(not(o__false2),[flies(tweety),not(-flies(tweety))]).
pr_rule(not(o__false3(_X0)),[not(-flies(_X0))]).
pr_rule(not(o__false3(_X0)),[-flies(_X0),not(flies(_X0))]).
pr_rule(not(o__false3),[forall(_X0,not(o__false3(_X0)))]).
pr_rule(not(o_false),[not(o__false1),not(o__false2),not(o__false3)]).
pr_rule(not(o__chk11),[not(flies(tux))]).
pr_rule(not(o__chk11),[flies(tux),not(-flies(tux))]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21),[not(flies(tweety))]).
pr_rule(not(o__chk21),[flies(tweety),not(-flies(tweety))]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o__chk31(_X0)),[not(-flies(_X0))]).
pr_rule(not(o__chk31(_X0)),[-flies(_X0),not(flies(_X0))]).
pr_rule(not(o__chk31),[forall(_X0,not(o__chk31(_X0)))]).
pr_rule(not(o_chk3),[not(o__chk31)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2),not(o_chk3)]).
pr_rule(add_to_query,[o_nmr_check]).
