pr_rule(p,[not(t)]).
pr_rule(t,[not(q)]).
pr_rule(q,[not(r),u,not(q)]).
pr_rule(r,[s]).
pr_rule(s,[p]).
pr_rule(not(o_s1),[not(p)]).
pr_rule(not(s),[not(o_s1)]).
pr_rule(not(u),[]).
pr_rule(not(o_r1),[not(s)]).
pr_rule(not(r),[not(o_r1)]).
pr_rule(not(o_q1),[r]).
pr_rule(not(o_q1),[not(r),not(u)]).
pr_rule(not(o_q1),[not(r),u,q]).
pr_rule(not(q),[not(o_q1)]).
pr_rule(not(o_t1),[q]).
pr_rule(not(t),[not(o_t1)]).
pr_rule(not(o_p1),[t]).
pr_rule(not(p),[not(o_p1)]).
pr_rule(not(o__false1),[not(r)]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11),[not(r)]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21),[t]).
pr_rule(not(o__chk21),[not(t),p]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o__chk31),[r]).
pr_rule(not(o__chk31),[not(r),not(u)]).
pr_rule(not(o__chk31),[not(r),u,q]).
pr_rule(not(o_chk3),[not(o__chk31)]).
pr_rule(not(o__chk41),[not(s)]).
pr_rule(not(o__chk41),[s,r]).
pr_rule(not(o_chk4),[not(o__chk41)]).
pr_rule(not(o__chk51),[not(p)]).
pr_rule(not(o__chk51),[p,s]).
pr_rule(not(o_chk5),[not(o__chk51)]).
pr_rule(not(o__chk61),[q]).
pr_rule(not(o__chk61),[not(q),t]).
pr_rule(not(o_chk6),[not(o__chk61)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2),not(o_chk3),not(o_chk4),not(o_chk5),not(o_chk6)]).
pr_rule(add_to_query,[o_nmr_check]).
