pr_rule(a,[b,c]).
pr_rule(a,[d,c]).
pr_rule(a,[c,b,e]).
pr_rule(c,[not(e)]).
pr_rule(e,[not(c)]).
pr_rule(b,[not(d)]).
pr_rule(d,[not(b)]).
pr_rule(not(o_e1),[c]).
pr_rule(not(e),[not(o_e1)]).
pr_rule(not(o_d_d1),[b]).
pr_rule(not(d),[not(o_d_d1)]).
pr_rule(not(o_d_c1),[e]).
pr_rule(not(c),[not(o_d_c1)]).
pr_rule(not(o_b1),[d]).
pr_rule(not(b),[not(o_b1)]).
pr_rule(not(o_a1),[not(b)]).
pr_rule(not(o_a1),[b,not(c)]).
pr_rule(not(o_a2),[not(d)]).
pr_rule(not(o_a2),[d,not(c)]).
pr_rule(not(o_a3),[not(c)]).
pr_rule(not(o_a3),[c,not(b)]).
pr_rule(not(o_a3),[c,b,not(e)]).
pr_rule(not(a),[not(o_a1),not(o_a2),not(o_a3)]).
pr_rule(not(o__false1),[a]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11),[a]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1)]).
pr_rule(add_to_query,[o_nmr_check]).
