pr_rule(p,[not(q)]).
pr_rule(q,[not(p)]).
pr_rule(p,[r]).
pr_rule(r,[p]).
pr_rule(_out,[r]).
pr_rule(_out,[p]).
pr_rule(_out,[q]).
pr_rule(not(o_d__out1),[not(r)]).
pr_rule(not(o_d__out2),[not(p)]).
pr_rule(not(o_d__out3),[not(q)]).
pr_rule(not(_out),[not(o_d__out1),not(o_d__out2),not(o_d__out3)]).
pr_rule(not(o_r1),[not(p)]).
pr_rule(not(r),[not(o_r1)]).
pr_rule(not(o_q1),[p]).
pr_rule(not(q),[not(o_q1)]).
pr_rule(not(o_p1),[q]).
pr_rule(not(o_p2),[not(r)]).
pr_rule(not(p),[not(o_p1),not(o_p2)]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
