pr_rule(catch(X),[X=a]).
pr_rule(wait(X),[not(catch(X))]).
pr_rule(not(o_wait1(X)),[catch(X)]).
pr_rule(not(wait(_X0)),[not(o_wait1(_X0))]).
pr_rule(not(o_catch1(X)),[X\=a]).
pr_rule(not(catch(_X0)),[not(o_catch1(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
