pr_rule(penguin(sam),[]).
pr_rule(wounded_bird(john),[]).
pr_rule(bird(tweety),[]).
pr_rule(bird(X),[penguin(X)]).
pr_rule(bird(X),[wounded_bird(X)]).
pr_rule(ab(X),[penguin(X)]).
pr_rule(ab(X),[wounded_bird(X)]).
pr_rule(flies(X),[bird(X),not(ab(X))]).
pr_rule(-flies(X),[ab(X)]).
pr_rule(-flies(X),[-bird(X)]).
pr_rule(-wounded_bird(X),[not(wounded_bird(X))]).
pr_rule(-bird(X),[not(bird(X))]).
pr_rule(-penguin(X),[not(penguin(X))]).
pr_rule(-ab(X),[not(ab(X))]).
pr_rule(not(o_c_ab1(X)),[ab(X)]).
pr_rule(not(-ab(_X0)),[not(o_c_ab1(_X0))]).
pr_rule(not(o_c_penguin1(X)),[penguin(X)]).
pr_rule(not(-penguin(_X0)),[not(o_c_penguin1(_X0))]).
pr_rule(not(o_c_wounded_bird1(X)),[wounded_bird(X)]).
pr_rule(not(-wounded_bird(_X0)),[not(o_c_wounded_bird1(_X0))]).
pr_rule(not(o_c_bird1(X)),[bird(X)]).
pr_rule(not(-bird(_X0)),[not(o_c_bird1(_X0))]).
pr_rule(not(o_c_flies1(X)),[not(ab(X))]).
pr_rule(not(o_c_flies2(X)),[not(-bird(X))]).
pr_rule(not(-flies(_X0)),[not(o_c_flies1(_X0)),not(o_c_flies2(_X0))]).
pr_rule(not(o_flies1(X)),[not(bird(X))]).
pr_rule(not(o_flies1(X)),[bird(X),ab(X)]).
pr_rule(not(flies(_X0)),[not(o_flies1(_X0))]).
pr_rule(not(o_ab1(X)),[not(penguin(X))]).
pr_rule(not(o_ab2(X)),[not(wounded_bird(X))]).
pr_rule(not(ab(_X0)),[not(o_ab1(_X0)),not(o_ab2(_X0))]).
pr_rule(not(o_bird1(_X0)),[_X0\=tweety]).
pr_rule(not(o_bird2(X)),[not(penguin(X))]).
pr_rule(not(o_bird3(X)),[not(wounded_bird(X))]).
pr_rule(not(bird(_X0)),[not(o_bird1(_X0)),not(o_bird2(_X0)),not(o_bird3(_X0))]).
pr_rule(not(o_wounded_bird1(_X0)),[_X0\=john]).
pr_rule(not(wounded_bird(_X0)),[not(o_wounded_bird1(_X0))]).
pr_rule(not(o_penguin1(_X0)),[_X0\=sam]).
pr_rule(not(penguin(_X0)),[not(o_penguin1(_X0))]).
pr_rule(not(o__false1(_X0)),[not(-ab(_X0))]).
pr_rule(not(o__false1(_X0)),[-ab(_X0),not(ab(_X0))]).
pr_rule(not(o__false1),[forall(_X0,not(o__false1(_X0)))]).
pr_rule(not(o__false2(_X0)),[not(-penguin(_X0))]).
pr_rule(not(o__false2(_X0)),[-penguin(_X0),not(penguin(_X0))]).
pr_rule(not(o__false2),[forall(_X0,not(o__false2(_X0)))]).
pr_rule(not(o__false3(_X0)),[not(-wounded_bird(_X0))]).
pr_rule(not(o__false3(_X0)),[-wounded_bird(_X0),not(wounded_bird(_X0))]).
pr_rule(not(o__false3),[forall(_X0,not(o__false3(_X0)))]).
pr_rule(not(o__false4(_X0)),[not(-bird(_X0))]).
pr_rule(not(o__false4(_X0)),[-bird(_X0),not(bird(_X0))]).
pr_rule(not(o__false4),[forall(_X0,not(o__false4(_X0)))]).
pr_rule(not(o__false5(_X0)),[not(-flies(_X0))]).
pr_rule(not(o__false5(_X0)),[-flies(_X0),not(flies(_X0))]).
pr_rule(not(o__false5),[forall(_X0,not(o__false5(_X0)))]).
pr_rule(not(o_false),[not(o__false1),not(o__false2),not(o__false3),not(o__false4),not(o__false5)]).
pr_rule(not(o__chk11(_X0)),[not(-ab(_X0))]).
pr_rule(not(o__chk11(_X0)),[-ab(_X0),not(ab(_X0))]).
pr_rule(not(o__chk11),[forall(_X0,not(o__chk11(_X0)))]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21(_X0)),[not(-penguin(_X0))]).
pr_rule(not(o__chk21(_X0)),[-penguin(_X0),not(penguin(_X0))]).
pr_rule(not(o__chk21),[forall(_X0,not(o__chk21(_X0)))]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o__chk31(_X0)),[not(-wounded_bird(_X0))]).
pr_rule(not(o__chk31(_X0)),[-wounded_bird(_X0),not(wounded_bird(_X0))]).
pr_rule(not(o__chk31),[forall(_X0,not(o__chk31(_X0)))]).
pr_rule(not(o_chk3),[not(o__chk31)]).
pr_rule(not(o__chk41(_X0)),[not(-bird(_X0))]).
pr_rule(not(o__chk41(_X0)),[-bird(_X0),not(bird(_X0))]).
pr_rule(not(o__chk41),[forall(_X0,not(o__chk41(_X0)))]).
pr_rule(not(o_chk4),[not(o__chk41)]).
pr_rule(not(o__chk51(_X0)),[not(-flies(_X0))]).
pr_rule(not(o__chk51(_X0)),[-flies(_X0),not(flies(_X0))]).
pr_rule(not(o__chk51),[forall(_X0,not(o__chk51(_X0)))]).
pr_rule(not(o_chk5),[not(o__chk51)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2),not(o_chk3),not(o_chk4),not(o_chk5)]).
pr_rule(add_to_query,[o_nmr_check]).
