pr_rule(node(a),[]).
pr_rule(node(b),[]).
pr_rule(node(c),[]).
pr_rule(node(d),[]).
pr_rule(node(e),[]).
pr_rule(edge(a,b),[]).
pr_rule(edge(a,c),[]).
pr_rule(edge(b,c),[]).
pr_rule(edge(d,e),[]).
pr_rule(path(X,X),[]).
pr_rule(path(X,Y),[edge(X,Z),path(Z,Y)]).
pr_rule(not(o_path1(X,_X1)),[_X1\=X]).
pr_rule(not(o_path2(X,Y,Z)),[not(edge(X,Z))]).
pr_rule(not(o_path2(X,Y,Z)),[edge(X,Z),not(path(Z,Y))]).
pr_rule(not(o_path2(X,Y)),[forall(Z,not(o_path2(X,Y,Z)))]).
pr_rule(not(path(_X0,_X1)),[not(o_path1(_X0,_X1)),not(o_path2(_X0,_X1))]).
pr_rule(not(o_edge1(_X0,_X1)),[_X0\=a]).
pr_rule(not(o_edge1(_X0,_X1)),[_X0=a,_X1\=b]).
pr_rule(not(o_edge2(_X0,_X1)),[_X0\=a]).
pr_rule(not(o_edge2(_X0,_X1)),[_X0=a,_X1\=c]).
pr_rule(not(o_edge3(_X0,_X1)),[_X0\=b]).
pr_rule(not(o_edge3(_X0,_X1)),[_X0=b,_X1\=c]).
pr_rule(not(o_edge4(_X0,_X1)),[_X0\=d]).
pr_rule(not(o_edge4(_X0,_X1)),[_X0=d,_X1\=e]).
pr_rule(not(edge(_X0,_X1)),[not(o_edge1(_X0,_X1)),not(o_edge2(_X0,_X1)),not(o_edge3(_X0,_X1)),not(o_edge4(_X0,_X1))]).
pr_rule(not(o_node1(_X0)),[_X0\=a]).
pr_rule(not(o_node2(_X0)),[_X0\=b]).
pr_rule(not(o_node3(_X0)),[_X0\=c]).
pr_rule(not(o_node4(_X0)),[_X0\=d]).
pr_rule(not(o_node5(_X0)),[_X0\=e]).
pr_rule(not(node(_X0)),[not(o_node1(_X0)),not(o_node2(_X0)),not(o_node3(_X0)),not(o_node4(_X0)),not(o_node5(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
