pr_rule(r(X,Y),[r(X,Z),p(Z,Y)]).
pr_rule(r(X,Y),[p(X,Y)]).
pr_rule(r(X,Y),[r(X,Z),q(Z,Y)]).
pr_rule(p(a,b),[]).
pr_rule(p(b,c),[]).
pr_rule(q(c,d),[]).
pr_rule(not(o_q1(_X0,_X1)),[_X0\=c]).
pr_rule(not(o_q1(_X0,_X1)),[_X0=c,_X1\=d]).
pr_rule(not(q(_X0,_X1)),[not(o_q1(_X0,_X1))]).
pr_rule(not(o_p1(_X0,_X1)),[_X0\=a]).
pr_rule(not(o_p1(_X0,_X1)),[_X0=a,_X1\=b]).
pr_rule(not(o_p2(_X0,_X1)),[_X0\=b]).
pr_rule(not(o_p2(_X0,_X1)),[_X0=b,_X1\=c]).
pr_rule(not(p(_X0,_X1)),[not(o_p1(_X0,_X1)),not(o_p2(_X0,_X1))]).
pr_rule(not(o_r1(X,Y,Z)),[not(r(X,Z))]).
pr_rule(not(o_r1(X,Y,Z)),[r(X,Z),not(p(Z,Y))]).
pr_rule(not(o_r1(X,Y)),[forall(Z,not(o_r1(X,Y,Z)))]).
pr_rule(not(o_r2(X,Y)),[not(p(X,Y))]).
pr_rule(not(o_r3(X,Y,Z)),[not(r(X,Z))]).
pr_rule(not(o_r3(X,Y,Z)),[r(X,Z),not(q(Z,Y))]).
pr_rule(not(o_r3(X,Y)),[forall(Z,not(o_r3(X,Y,Z)))]).
pr_rule(not(r(_X0,_X1)),[not(o_r1(_X0,_X1)),not(o_r2(_X0,_X1)),not(o_r3(_X0,_X1))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
