pr_rule(s(0),[]).
pr_rule(s(s(X)),[s(X)]).
pr_rule(sum(s(0),X,s(X)),[]).
pr_rule(sum(X,s(0),s(X)),[]).
pr_rule(sum(s(X),Y,s(Z)),[X\=0,sum(X,Y,Z)]).
pr_rule(sumlist([X|T],[Y|T2],[Z|T3]),[sum(X,Y,Z),sumlist(T,T2,T3)]).
pr_rule(sumlist([],[],[]),[]).
pr_rule(not(o_sumlist1(_Z0,_Z1,_Z2,X,T,Y,T2,Z,T3)),[_Z0\=[X|T]]).
pr_rule(not(o_sumlist1(_Z0,_Z1,_Z2,X,T,Y,T2,Z,T3)),[_Z0=[X|T],_Z1\=[Y|T2]]).
pr_rule(not(o_sumlist1(_Z0,_Z1,_Z2,X,T,Y,T2,Z,T3)),[_Z0=[X|T],_Z1=[Y|T2],_Z2\=[Z|T3]]).
pr_rule(not(o_sumlist1(_Z0,_Z1,_Z2,X,T,Y,T2,Z,T3)),[_Z0=[X|T],_Z1=[Y|T2],_Z2=[Z|T3],not(sum(X,Y,Z))]).
pr_rule(not(o_sumlist1(_Z0,_Z1,_Z2,X,T,Y,T2,Z,T3)),[_Z0=[X|T],_Z1=[Y|T2],_Z2=[Z|T3],sum(X,Y,Z),not(sumlist(T,T2,T3))]).
pr_rule(not(o_sumlist1(_Z0,_Z1,_Z2)),[forall(X,forall(T,forall(Y,forall(T2,forall(Z,forall(T3,not(o_sumlist1(_Z0,_Z1,_Z2,X,T,Y,T2,Z,T3))))))))]).
pr_rule(not(o_sumlist2(_X0,_X1,_X2)),[_X0\=[]]).
pr_rule(not(o_sumlist2(_X0,_X1,_X2)),[_X0=[],_X1\=[]]).
pr_rule(not(o_sumlist2(_X0,_X1,_X2)),[_X0=[],_X1=[],_X2\=[]]).
pr_rule(not(sumlist(_X0,_X1,_X2)),[not(o_sumlist1(_X0,_X1,_X2)),not(o_sumlist2(_X0,_X1,_X2))]).
pr_rule(not(o_sum1(_Z0,X,_Z1)),[_Z0\=s(0)]).
pr_rule(not(o_sum1(_Z0,X,_Z1)),[_Z0=s(0),_Z1\=s(X)]).
pr_rule(not(o_sum2(X,_Z0,_Z1)),[_Z0\=s(0)]).
pr_rule(not(o_sum2(X,_Z0,_Z1)),[_Z0=s(0),_Z1\=s(X)]).
pr_rule(not(o_sum3(_Z0,Y,_Z1,X,Z)),[_Z0\=s(X)]).
pr_rule(not(o_sum3(_Z0,Y,_Z1,X,Z)),[_Z0=s(X),_Z1\=s(Z)]).
pr_rule(not(o_sum3(_Z0,Y,_Z1,X,Z)),[_Z0=s(X),_Z1=s(Z),X=0]).
pr_rule(not(o_sum3(_Z0,Y,_Z1,X,Z)),[_Z0=s(X),_Z1=s(Z),X\=0,not(sum(X,Y,Z))]).
pr_rule(not(o_sum3(_Z0,Y,_Z1)),[forall(X,forall(Z,not(o_sum3(_Z0,Y,_Z1,X,Z))))]).
pr_rule(not(sum(_X0,_X1,_X2)),[not(o_sum1(_X0,_X1,_X2)),not(o_sum2(_X0,_X1,_X2)),not(o_sum3(_X0,_X1,_X2))]).
pr_rule(not(o_s1(_X0)),[_X0\=0]).
pr_rule(not(o_s2(_Z0,X)),[_Z0\=s(X)]).
pr_rule(not(o_s2(_Z0,X)),[_Z0=s(X),not(s(X))]).
pr_rule(not(o_s2(_Z0)),[forall(X,not(o_s2(_Z0,X)))]).
pr_rule(not(s(_X0)),[not(o_s1(_X0)),not(o_s2(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
