pr_rule(alpha(a),[]).
pr_rule(alpha(b),[]).
pr_rule(alpha(c),[]).
pr_rule(alpha_num(a),[]).
pr_rule(alpha_num(d),[]).
pr_rule(alpha_num(e),[]).
pr_rule(alpha_num(0),[]).
pr_rule(alpha_num(1),[]).
pr_rule(alpha_num(2),[]).
pr_rule(alpha_spec(e),[]).
pr_rule(alpha_spec(f),[]).
pr_rule(alpha_spec(g),[]).
pr_rule(alpha_spec(#),[]).
pr_rule(alpha_spec(&),[]).
pr_rule(member(X,[X|T]),[]).
pr_rule(member(X,[_V2|T]),[member(X,T)]).
pr_rule(state1(L),[not(alpha(X)),not(member(X,L)),not(state2(L))]).
pr_rule(state1(X),[]).
pr_rule(state2(L),[not(state3(L))]).
pr_rule(state3(L),[not(state1(L))]).
pr_rule(not(o_state31(L)),[state1(L)]).
pr_rule(not(state3(_X0)),[not(o_state31(_X0))]).
pr_rule(not(o_state21(L)),[state3(L)]).
pr_rule(not(state2(_X0)),[not(o_state21(_X0))]).
pr_rule(not(o_state11(L,X)),[alpha(X)]).
pr_rule(not(o_state11(L,X)),[not(alpha(X)),member(X,L)]).
pr_rule(not(o_state11(L,X)),[not(alpha(X)),not(member(X,L)),state2(L)]).
pr_rule(not(o_state11(L)),[forall(X,not(o_state11(L,X)))]).
pr_rule(not(state1(_X0)),[not(o_state11(_X0)),not(o_state12(_X0))]).
pr_rule(not(o_member1(X,_Z0,T)),[_Z0\=[X|T]]).
pr_rule(not(o_member1(X,_Z0)),[forall(T,not(o_member1(X,_Z0,T)))]).
pr_rule(not(o_member2(X,_Z0,_V2,T)),[_Z0\=[_V2|T]]).
pr_rule(not(o_member2(X,_Z0,_V2,T)),[_Z0=[_V2|T],not(member(X,T))]).
pr_rule(not(o_member2(X,_Z0)),[forall(_V2,forall(T,not(o_member2(X,_Z0,_V2,T))))]).
pr_rule(not(member(_X0,_X1)),[not(o_member1(_X0,_X1)),not(o_member2(_X0,_X1))]).
pr_rule(not(o_alpha_spec1(_X0)),[_X0\=e]).
pr_rule(not(o_alpha_spec2(_X0)),[_X0\=f]).
pr_rule(not(o_alpha_spec3(_X0)),[_X0\=g]).
pr_rule(not(o_alpha_spec4(_X0)),[_X0\= #]).
pr_rule(not(o_alpha_spec5(_X0)),[_X0\= &]).
pr_rule(not(alpha_spec(_X0)),[not(o_alpha_spec1(_X0)),not(o_alpha_spec2(_X0)),not(o_alpha_spec3(_X0)),not(o_alpha_spec4(_X0)),not(o_alpha_spec5(_X0))]).
pr_rule(not(o_alpha_num1(_X0)),[_X0\=a]).
pr_rule(not(o_alpha_num2(_X0)),[_X0\=d]).
pr_rule(not(o_alpha_num3(_X0)),[_X0\=e]).
pr_rule(not(o_alpha_num4(_X0)),[_X0\=0]).
pr_rule(not(o_alpha_num5(_X0)),[_X0\=1]).
pr_rule(not(o_alpha_num6(_X0)),[_X0\=2]).
pr_rule(not(alpha_num(_X0)),[not(o_alpha_num1(_X0)),not(o_alpha_num2(_X0)),not(o_alpha_num3(_X0)),not(o_alpha_num4(_X0)),not(o_alpha_num5(_X0)),not(o_alpha_num6(_X0))]).
pr_rule(not(o_alpha1(_X0)),[_X0\=a]).
pr_rule(not(o_alpha2(_X0)),[_X0\=b]).
pr_rule(not(o_alpha3(_X0)),[_X0\=c]).
pr_rule(not(alpha(_X0)),[not(o_alpha1(_X0)),not(o_alpha2(_X0)),not(o_alpha3(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o__chk11(L,X)),[alpha(X)]).
pr_rule(not(o__chk11(L,X)),[not(alpha(X)),member(X,L)]).
pr_rule(not(o__chk11(L,X)),[not(alpha(X)),not(member(X,L)),state2(L)]).
pr_rule(not(o__chk11(L,X)),[not(alpha(X)),not(member(X,L)),not(state2(L)),state1(L)]).
pr_rule(not(o__chk11(L)),[forall(X,not(o__chk11(L,X)))]).
pr_rule(not(o_chk1(_X0)),[not(o__chk11(_X0))]).
pr_rule(not(o__chk21(L)),[state3(L)]).
pr_rule(not(o__chk21(L)),[not(state3(L)),state2(L)]).
pr_rule(not(o_chk2(_X0)),[not(o__chk21(_X0))]).
pr_rule(not(o__chk31(L)),[state1(L)]).
pr_rule(not(o__chk31(L)),[not(state1(L)),state3(L)]).
pr_rule(not(o_chk3(_X0)),[not(o__chk31(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[forall(_X0,not(o_chk1(_X0))),forall(_X0,not(o_chk2(_X0))),forall(_X0,not(o_chk3(_X0)))]).
pr_rule(add_to_query,[o_nmr_check]).
