pr_rule(q(a),[]).
pr_rule(q(b),[]).
pr_rule(q(c),[]).
pr_rule(p(X),[p(Y)]).
pr_rule(not(o_p1(X,Y)),[not(p(Y))]).
pr_rule(not(o_p1(X)),[forall(Y,not(o_p1(X,Y)))]).
pr_rule(not(p(_X0)),[not(o_p1(_X0))]).
pr_rule(not(o_q1(_X0)),[_X0\=a]).
pr_rule(not(o_q2(_X0)),[_X0\=b]).
pr_rule(not(o_q3(_X0)),[_X0\=c]).
pr_rule(not(q(_X0)),[not(o_q1(_X0)),not(o_q2(_X0)),not(o_q3(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
