pr_rule(n(0),[]).
pr_rule(n(s(X)),[n(X)]).
pr_rule(not(o_d_n1(_X0)),[_X0\=0]).
pr_rule(not(o_d_n2(_Z0,X)),[_Z0\=s(X)]).
pr_rule(not(o_d_n2(_Z0,X)),[_Z0=s(X),not(n(X))]).
pr_rule(not(o_d_n2(_Z0)),[forall(X,not(o_d_n2(_Z0,X)))]).
pr_rule(not(n(_X0)),[not(o_d_n1(_X0)),not(o_d_n2(_X0))]).
pr_rule(not(o_false),[]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[]).
pr_rule(add_to_query,[o_nmr_check]).
