pr_rule(p,[not(q)]).
pr_rule(q,[not(r)]).
pr_rule(r,[not(p)]).
pr_rule(q,[not(p)]).
pr_rule(not(o_r1),[p]).
pr_rule(not(r),[not(o_r1)]).
pr_rule(not(o_q1),[r]).
pr_rule(not(o_q2),[p]).
pr_rule(not(q),[not(o_q1),not(o_q2)]).
pr_rule(not(o_p1),[q]).
pr_rule(not(p),[not(o_p1)]).
pr_rule(not(o__false1),[q]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11),[q]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21),[q]).
pr_rule(not(o__chk21),[not(q),p]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o__chk31),[r]).
pr_rule(not(o__chk31),[not(r),q]).
pr_rule(not(o_chk3),[not(o__chk31)]).
pr_rule(not(o__chk41),[p]).
pr_rule(not(o__chk41),[not(p),r]).
pr_rule(not(o_chk4),[not(o__chk41)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2),not(o_chk3),not(o_chk4)]).
pr_rule(add_to_query,[o_nmr_check]).
