pr_rule(p,[q,r]).
pr_rule(q,[not(s)]).
pr_rule(r,[not(t)]).
pr_rule(r,[not(p)]).
pr_rule(not(t),[]).
pr_rule(not(s),[]).
pr_rule(not(o_r1),[t]).
pr_rule(not(o_r2),[p]).
pr_rule(not(r),[not(o_r1),not(o_r2)]).
pr_rule(not(o_q1),[s]).
pr_rule(not(q),[not(o_q1)]).
pr_rule(not(o_p1),[not(q)]).
pr_rule(not(o_p1),[q,not(r)]).
pr_rule(not(p),[not(o_p1)]).
pr_rule(not(o__false1),[q]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11),[q]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21),[not(q)]).
pr_rule(not(o__chk21),[q,not(r)]).
pr_rule(not(o__chk21),[q,r,p]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o__chk31),[p]).
pr_rule(not(o__chk31),[not(p),r]).
pr_rule(not(o_chk3),[not(o__chk31)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2),not(o_chk3)]).
pr_rule(add_to_query,[o_nmr_check]).
