pr_rule(bird(tweety),[]).
pr_rule(flies(tweety),[bird(tweety),not(-flies(tweety))]).
pr_rule(-flies(tweety),[bird(tweety),not(flies(tweety))]).
pr_rule(not(o_c_flies1(_X0)),[_X0\=tweety]).
pr_rule(not(o_c_flies1(_X0)),[_X0=tweety,not(bird(tweety))]).
pr_rule(not(o_c_flies1(_X0)),[_X0=tweety,bird(tweety),flies(tweety)]).
pr_rule(not(-flies(_X0)),[not(o_c_flies1(_X0))]).
pr_rule(not(o_flies1(_X0)),[_X0\=tweety]).
pr_rule(not(o_flies1(_X0)),[_X0=tweety,not(bird(tweety))]).
pr_rule(not(o_flies1(_X0)),[_X0=tweety,bird(tweety),-flies(tweety)]).
pr_rule(not(flies(_X0)),[not(o_flies1(_X0))]).
pr_rule(not(o_bird1(_X0)),[_X0\=tweety]).
pr_rule(not(bird(_X0)),[not(o_bird1(_X0))]).
pr_rule(not(o__false1(_X0)),[not(-flies(_X0))]).
pr_rule(not(o__false1(_X0)),[-flies(_X0),not(flies(_X0))]).
pr_rule(not(o__false1),[forall(_X0,not(o__false1(_X0)))]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11(_X0)),[not(-flies(_X0))]).
pr_rule(not(o__chk11(_X0)),[-flies(_X0),not(flies(_X0))]).
pr_rule(not(o__chk11),[forall(_X0,not(o__chk11(_X0)))]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1)]).
pr_rule(add_to_query,[o_nmr_check]).
