pr_rule(p,[not(q)]).
pr_rule(q,[r,s]).
pr_rule(r,[p]).
pr_rule(not(s),[]).
pr_rule(not(o_r1),[not(p)]).
pr_rule(not(r),[not(o_r1)]).
pr_rule(not(o_q1),[not(r)]).
pr_rule(not(o_q1),[r,not(s)]).
pr_rule(not(q),[not(o_q1)]).
pr_rule(not(o_p1),[q]).
pr_rule(not(p),[not(o_p1)]).
pr_rule(not(o__false1),[p]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11),[p]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21),[q]).
pr_rule(not(o__chk21),[not(q),p]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o__chk31),[not(r)]).
pr_rule(not(o__chk31),[r,not(s)]).
pr_rule(not(o__chk31),[r,s,q]).
pr_rule(not(o_chk3),[not(o__chk31)]).
pr_rule(not(o__chk41),[not(p)]).
pr_rule(not(o__chk41),[p,r]).
pr_rule(not(o_chk4),[not(o__chk41)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2),not(o_chk3),not(o_chk4)]).
pr_rule(add_to_query,[o_nmr_check]).
