pr_rule(p,[q,not(p),r]).
pr_rule(comp,[not(p),not(q),not(r)]).
pr_rule(not(o_comp1),[p]).
pr_rule(not(o_comp1),[not(p),q]).
pr_rule(not(o_comp1),[not(p),not(q),r]).
pr_rule(not(comp),[not(o_comp1)]).
pr_rule(not(r),[]).
pr_rule(not(q),[]).
pr_rule(not(o_p1),[not(q)]).
pr_rule(not(o_p1),[q,p]).
pr_rule(not(o_p1),[q,not(p),not(r)]).
pr_rule(not(p),[not(o_p1)]).
pr_rule(not(o__false1),[comp]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11),[comp]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21),[not(q)]).
pr_rule(not(o__chk21),[q,p]).
pr_rule(not(o__chk21),[q,not(p),not(r)]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2)]).
pr_rule(add_to_query,[o_nmr_check]).
