pr_rule(p,[not(q),r]).
pr_rule(p,[not(r),q]).
pr_rule(r,[not(q)]).
pr_rule(q,[not(r)]).
pr_rule(not(o_r1),[q]).
pr_rule(not(r),[not(o_r1)]).
pr_rule(not(o_q1),[r]).
pr_rule(not(q),[not(o_q1)]).
pr_rule(not(o_p1),[q]).
pr_rule(not(o_p1),[not(q),not(r)]).
pr_rule(not(o_p2),[r]).
pr_rule(not(o_p2),[not(r),not(q)]).
pr_rule(not(p),[not(o_p1),not(o_p2)]).
pr_rule(not(o__false1),[p]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11),[p]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1)]).
pr_rule(add_to_query,[o_nmr_check]).
