pr_rule(p,[q,not(p)]).
pr_rule(q,[]).
pr_rule(_out,[p]).
pr_rule(_out,[q]).
pr_rule(_out,[not(p)]).
pr_rule(_out,[not(q)]).
pr_rule(not(o_d__out1),[not(p)]).
pr_rule(not(o_d__out2),[not(q)]).
pr_rule(not(o_d__out3),[p]).
pr_rule(not(o_d__out4),[q]).
pr_rule(not(_out),[not(o_d__out1),not(o_d__out2),not(o_d__out3),not(o_d__out4)]).
pr_rule(not(q),[not(o_q1)]).
pr_rule(not(o_p1),[not(q)]).
pr_rule(not(o_p1),[q,p]).
pr_rule(not(p),[not(o_p1)]).
pr_rule(not(o__false1),[_out]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11),[_out]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21),[not(q)]).
pr_rule(not(o__chk21),[q,p]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2)]).
pr_rule(add_to_query,[o_nmr_check]).
