pr_rule(a,[not(b)]).
pr_rule(b,[not(a)]).
pr_rule(c,[not(d)]).
pr_rule(d,[not(c)]).
pr_rule(not(o_d_d1),[c]).
pr_rule(not(d),[not(o_d_d1)]).
pr_rule(not(o_d_c1),[d]).
pr_rule(not(c),[not(o_d_c1)]).
pr_rule(not(o_b1),[a]).
pr_rule(not(b),[not(o_b1)]).
pr_rule(not(o_a1),[b]).
pr_rule(not(a),[not(o_a1)]).
pr_rule(not(o__false1),[not(a)]).
pr_rule(not(o__false1),[a,not(d)]).
pr_rule(not(o__false2),[not(a)]).
pr_rule(not(o__false2),[a,not(c)]).
pr_rule(not(o__false3),[not(b)]).
pr_rule(not(o__false3),[b,not(c)]).
pr_rule(not(o__false4),[not(b)]).
pr_rule(not(o__false4),[b,not(d)]).
pr_rule(not(o_false),[not(o__false1),not(o__false2),not(o__false3),not(o__false4)]).
pr_rule(not(o__chk11),[not(a)]).
pr_rule(not(o__chk11),[a,not(d)]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o__chk21),[not(a)]).
pr_rule(not(o__chk21),[a,not(c)]).
pr_rule(not(o_chk2),[not(o__chk21)]).
pr_rule(not(o__chk31),[not(b)]).
pr_rule(not(o__chk31),[b,not(c)]).
pr_rule(not(o_chk3),[not(o__chk31)]).
pr_rule(not(o__chk41),[not(b)]).
pr_rule(not(o__chk41),[b,not(d)]).
pr_rule(not(o_chk4),[not(o__chk41)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1),not(o_chk2),not(o_chk3),not(o_chk4)]).
pr_rule(add_to_query,[o_nmr_check]).
