pr_rule(p(X),[not(q(X,Y))]).
pr_rule(q(X,Y),[not(p(X)),s(Y)]).
pr_rule(r,[q(C,C)]).
pr_rule(s(_V1),[]).
pr_rule(not(o_r1(C)),[not(q(C,C))]).
pr_rule(not(o_r1),[forall(C,not(o_r1(C)))]).
pr_rule(not(r),[not(o_r1)]).
pr_rule(not(s(_X0)),[not(o_s1(_X0))]).
pr_rule(not(o_q1(X,Y)),[p(X)]).
pr_rule(not(o_q1(X,Y)),[not(p(X)),not(s(Y))]).
pr_rule(not(q(_X0,_X1)),[not(o_q1(_X0,_X1))]).
pr_rule(not(o_p1(X,Y)),[q(X,Y)]).
pr_rule(not(o_p1(X)),[forall(Y,not(o_p1(X,Y)))]).
pr_rule(not(p(_X0)),[not(o_p1(_X0))]).
pr_rule(not(o__false1(X,Z)),[not(p(X))]).
pr_rule(not(o__false1(X,Z)),[p(X),Z=7]).
pr_rule(not(o__false1(X,Z)),[p(X),Z\=7,not(q(Z,0))]).
pr_rule(not(o__false1),[forall(X,forall(Z,not(o__false1(X,Z))))]).
pr_rule(not(o_false),[not(o__false1)]).
pr_rule(not(o__chk11(X,Z)),[not(p(X))]).
pr_rule(not(o__chk11(X,Z)),[p(X),Z=7]).
pr_rule(not(o__chk11(X,Z)),[p(X),Z\=7,not(q(Z,0))]).
pr_rule(not(o__chk11),[forall(X,forall(Z,not(o__chk11(X,Z))))]).
pr_rule(not(o_chk1),[not(o__chk11)]).
pr_rule(not(o_false),[]).
pr_rule(o_nmr_check,[not(o_chk1)]).
pr_rule(add_to_query,[o_nmr_check]).
